alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
egress:
  type: DEDICATED_IP
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: node-hello
    match:
      path:
        prefix: /
name: internal-service-app
region: blr
services:
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: ksai7991/node-hello
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  log_destinations:
  - logtail:
      token: qTMoi6Rk9MXbjtLRTPvnvhPC
    name: logtail
  name: node-hello
  run_command: npm start
  source_dir: /
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: ksai7991/node-express-hello-world
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 8080
  log_destinations:
  - logtail:
      token: qTMoi6Rk9MXbjtLRTPvnvhPC
    name: logtail
  name: internal-app1
  run_command: npm start
  source_dir: /
