features:
- buildpack-stack=ubuntu-22
envs:
- key: VITE_SUPABASE_URL
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:RfxVts7ARTJSYrCezD/GvbURyRHCnslD:yx27qaGTOSIrHb7/RFgVhQ/RDTSX3dh6muTKCdXzsEi36vjzpr8j4vl1pSKf49x2RNtz/2VQ21o=]
- key: VITE_SUPABASE_URL_ANOTHER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:RfxVts7ARTJSYrCezD/GvbURyRHCnslD:yx27qaGTOSIrHb7/RFgVhQ/RDTSX3dh6muTKCdXzsEi36vjzpr8j4vl1pSKf49x2RNtz/2VQ21o=]
functions:
- git:
    branch: master
    repo_clone_url: https://github.com/digitalocean/sample-functions-nodejs-helloworld.git
  name: sample-functions-nodejs-hellowor
  source_dir: /
ingress:
  rules:
  - component:
      name: node-hello
    match:
      path:
        prefix: /
  - component:
      name: sample-functions-nodejs-hellowor
    match:
      path:
        prefix: /sample-functions-nodejs-hellowor
name: internal-service-app1
region: blr
services:
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: ksai7991/node-hello
  http_port: 8080
  instance_count: 3
  instance_size_slug: apps-s-2vcpu-4gb
  log_destinations:
  - logtail:
      token: qTMoi6Rk9MXbjtLRTPvnvhPC
    name: logtail
  name: node-hello
  run_command: npm start
  source_dir: /
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: ksai7991/node-express-hello-world
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 8080
  log_destinations:
  - logtail:
      token: qTMoi6Rk9MXbjtLRTPvnvhPC
    name: logtail
  name: internal-app1
  run_command: npm start
  source_dir: /
